# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9809a147d99843a05e77c52fdd3dc55e3ee256026eb311aede35a9f5a4fa04541089ee5336b5bbc938aafd7e2d08d85f30626dba3aef0014cfb031e41f5efbcb

test:
  secret_key_base: fb56ae683a40b426220f5907010dd95412b766d4d3197681c6d5cd56535e61ff9a350070a9cfcb1477f7c84d6c0a3205880b7c2d59fa9ca799ae9eec988f1f3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
